### ISSUE TITLE
 Implement "Random" button for practice

### ISSUE THREAD

**Issue by puppe1990** [puppe1990/kids-english-learning#1]
## Description:

Currently, the user can only select letters or numbers in a linear fashion. It would be beneficial to have a "random" button that, when clicked, randomly selects a letter or number for the user to practice. This would add an element of unpredictability and make the practice sessions more engaging.

## Task List:

- [ ] Add a "random" button to the interface
- [ ] Implement a function that selects a random letter or number when the button is clicked
- [ ]  Update the selected letter/number display to reflect the randomly selected letter/number
- [ ] Add functionality to play the corresponding audio file for the randomly selected letter/number
- [ ] Test the feature to ensure it is working as expected

## Additional Information:

* This feature should be optional, so as not to disrupt the user's workflow if they prefer to select letters/numbers in order.
* The "random" button should be disabled when no letters or numbers are available for selection.
* The "random" button should be placed where it's easily accessible for the user.
